# Generated by Django 4.2.5 on 2023-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
    ]
