# Generated by Django 4.2.5 on 2023-09-09 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_listing_like_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="like_new",
        ),
    ]
